name: Check

on:
  push:
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Check
        run: pnpm run check
